call plug#begin('C:/Users/Luis/AppData/Local/nvim/plugged')
Plug 'tpope/vim-commentary'
Plug 'terryma/vim-multiple-cursors'
Plug 'sheerun/vim-polyglot'
Plug 'jiangmiao/auto-pairs'
call plug#end()

"General config
set hidden
set number
set relativenumber
set inccommand=split
set mouse=a
set encoding=UTF-8
set scrolloff=7
set tabstop=4
set softtabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set fileformat=unix
set expandtab
set autoindent
syntax on
syntax enable